//image/emoji/Unicode Character aibles
module.exports = {
  map: " \ud83d\uddfa ",
  people: " \ud83d\udc65 ",
  fireworks: " \ud83c\udf87 ",
  moneyBag: " \ud83d\udcb0 ",
  bug: " \ud83d\udc1b ",
  korona: "\u24C0",
  deckPlan: "\u2630 Deck Plan \u2630",
  navigation: " \ud83d\uddfa Navigation \ud83d\uddfa ",
  upDown: " \u2195 ",
  anchor: " \u2693 ",
  helm: "⎈",
  cocktail: "🍸",
  joker: " 🃏 ",
  gift: " 🎁 ",
  slots: "🎰",
  radio: "🔘",
  world: "🌎",
  books: "📚",
};
