const terms = {
'Atrium': `A lobby-like space where you’ll find the purser or guest services`,
'Beam': `The broadest part of the ship’s hull`,
'Berth': `The “parking spot” where the ship docks in a port of call, or a bed on a cruise ship`,
'Cabin steward': `The crew member who cleans and maintains your stateroom`,
'Captain': `The commander of the ship`,
'Cruise director': `The person responsible for managing onboard entertainment, activities and events`,
'Cruise documents': `The documents you receive before sailing, which may include the cruise ticket, a booklet and shore excursion information`,
'Deck plan': `An illustration that shows the location of the staterooms, restaurants and other facilities`,
'Disembarkation': `When you leave the ship at the end of the cruise`,
'Embarkation': `When you first board your ship`,
'Gangway': `The opening in the ship where passengers enter or exit`,
'Knot': `A measurement of the ship’s speed, which equals one nautical mile`,
'Leeward': `The side of a ship or island that’s sheltered from the wind`,
'Maiden voyage': `The first time a ship embarks on a voyage with passengers on board`,
"Maitre d’": `The crew member in charge of dining room services and operations`,
'Mooring': `The item used to secure the ship at the port`,
'Muster station': `The area where passengers gather in case of an emergency`,
'Purser': `The person responsible for customer service and handling billing services`,
'Roll': `The side-to-side movement experienced while cruising rough waters`,
'Stem': `Extreme forward part of a ship’s bow`,
'Tender': `A small boat that takes passengers to the shore if the ship is at anchor`,
'Wake': `The trail of waves seen at the rear of a ship as it moves forward`,
'Windward': `The windier side of a ship or island`,

'Aft': `The area near the ship’s stern at the rear of the ship`,
'Bow': `The front of the ship`,
'Bridge': `The area of the ship, typically located in the bow, where the captain and crew control and manage the vessel`,
'Cabin': `Your private onboard room, also known as a stateroom`,
'Decks': `The floors of the ship’s structure arranged in different levels, such as the lower, middle and upper decks`,
'Galley': `The ship’s kitchen`,
'Hull': `The main body of the ship`,
'Lido deck': `Where you’ll find the pool and typically other amenities such as restaurants, bars, and a fitness center`,
'Midship': `Toward the middle of the ship`,
'Port': `The left side of the ship when facing the bow`,
'Starboard': `The right side of the ship when facing the bow`,
'Stern': `The extreme rear of the ship`,

'Stateroom': `The stateroom is your private space where you sleep, relax and get ready for your day of adventure. Staterooms vary depending on your ship and may be small, frugal cabins or spacious accommodations with elegant touches.`,
'Crew space': `The crew space is the private area reserved for the ship’s staff and crew members, such as chefs, housekeepers and the captain. Crew members typically live on the lower deck, while staff members live on the upper deck. The captain and officers usually stay in private staterooms near the bridge.`,
'Public space': `The public space includes the areas all guests can enjoy, such as the pool, fitness center, library and restaurants.`, 
}
